### ISSUE TITLE
Some parts of the API haven't been implemented in the python-loklak-api yet

### ISSUE THREAD

**Issue by pythad** [sudheesh001/loklak-telegram-bridge#4]
It would be nice to implement `/suggest` and `/crawler` commands but they haven't been added to `python-loklak-api` yet. Do we need to add them to the python API firstly?

**Comment by sudheesh001** [comment]
Sure if you'd like to do this, please head over to `https://github.com/loklak/python-loklak-api` and you can fix it :+1: Or its in the roadmap, it'll be fixed soon :+1:
